name: Build and push images

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  LLVM_SLOT: 17

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.config.arch }} ${{ matrix.config.libc }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        config:
          - arch: aarch64
            libc: musl
          - arch: aarch64
            libc: gnu
          - arch: x86_64
            libc: musl

    steps:
      - uses: actions/checkout@v4

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule

      - name: Build and push image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.config.arch }}-${{ matrix.config.libc }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TARGET=${{ matrix.config.arch }}-unknown-linux-${{ matrix.config.libc }}
          file: Containerfile
          push: true
